//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ProductListByGroup1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DoAnCuoiKi.UserControls.ProductListByGroup ProductListByGroup1;
        
        /// <summary>
        /// ProductListByGroup2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DoAnCuoiKi.UserControls.ProductListByGroup ProductListByGroup2;
        
        /// <summary>
        /// ProductListByGroup3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DoAnCuoiKi.UserControls.ProductListByGroup ProductListByGroup3;
    }
}
