//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public int IDSP { get; set; }
        public string HinhAnhURL { get; set; }
        public bool LaAnhHienThi { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
